# Generated by Django 4.2.5 on 2023-09-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_user_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('jop', models.CharField(max_length=255)),
                ('Pass', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
