# Generated by Django 4.2.5 on 2023-09-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dw1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dw2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gasp1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gasp2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gt11',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gt12',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gt21',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gt22',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rw1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rw2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='st10',
            name='name',
        ),
        migrations.RemoveField(
            model_name='st20',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tranct1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tranct2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacuum1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacuum2',
            name='name',
        ),
    ]
