# Generated by Django 4.2.5 on 2023-09-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operating', '0003_lastvalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lastvalues',
            new_name='LastOperatingvalues',
        ),
    ]
