# Generated by Django 4.2.5 on 2023-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('Place', models.CharField(max_length=255)),
                ('Data', models.TextField()),
                ('Note', models.TextField()),
                ('Status', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('Place', models.CharField(max_length=255)),
                ('Data', models.TextField()),
                ('Note', models.TextField()),
                ('Status', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('Place', models.CharField(max_length=255)),
                ('Data', models.TextField()),
                ('Note', models.TextField()),
                ('Status', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
    ]
