# Generated by Django 4.2.5 on 2023-09-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HPD11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HPD21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HPMS11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HPMS21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPD11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPD21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPMS11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPMS21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LPD11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LPD21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LPMS11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LPMS21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
    ]
