# Generated by Django 4.2.5 on 2023-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPD12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HPD22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HPMS12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HPMS22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPD12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPD22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPMS12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPMS22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LastChemicalvalues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HPD11', models.CharField(max_length=5)),
                ('IPD11', models.CharField(max_length=5)),
                ('LPD11', models.CharField(max_length=5)),
                ('HPMS11', models.CharField(max_length=5)),
                ('IPMS11', models.CharField(max_length=5)),
                ('LPMS1', models.CharField(max_length=5)),
                ('HPD21', models.CharField(max_length=5)),
                ('IPD21', models.CharField(max_length=5)),
                ('LPD21', models.CharField(max_length=5)),
                ('HPMS21', models.CharField(max_length=5)),
                ('IPMS21', models.CharField(max_length=5)),
                ('LPMS21', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LPD12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LPD22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LPMS12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LPMS22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
    ]
