# Generated by Django 4.2.5 on 2023-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemical', '0002_hpd12_hpd22_hpms12_hpms22_ipd12_ipd22_ipms12_ipms22_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastChemicalvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HPD11', models.CharField(max_length=5)),
                ('IPD11', models.CharField(max_length=5)),
                ('LPD11', models.CharField(max_length=5)),
                ('HPMS11', models.CharField(max_length=5)),
                ('IPMS11', models.CharField(max_length=5)),
                ('LPMS11', models.CharField(max_length=5)),
                ('HPD12', models.CharField(max_length=5)),
                ('IPD12', models.CharField(max_length=5)),
                ('LPD12', models.CharField(max_length=5)),
                ('HPMS12', models.CharField(max_length=5)),
                ('IPMS12', models.CharField(max_length=5)),
                ('LPMS12', models.CharField(max_length=5)),
                ('HPD21', models.CharField(max_length=5)),
                ('IPD21', models.CharField(max_length=5)),
                ('LPD21', models.CharField(max_length=5)),
                ('HPMS21', models.CharField(max_length=5)),
                ('IPMS21', models.CharField(max_length=5)),
                ('LPMS21', models.CharField(max_length=5)),
                ('HPD22', models.CharField(max_length=5)),
                ('IPD22', models.CharField(max_length=5)),
                ('LPD22', models.CharField(max_length=5)),
                ('HPMS22', models.CharField(max_length=5)),
                ('IPMS22', models.CharField(max_length=5)),
                ('LPMS22', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='LastChemicalvalues',
        ),
    ]
